version: '3'
services:
  eureka-server:
    image: eureka-server
    container_name: eureka-server
    ports:
      - "8761:8761"
  db-service:
    image: db-service
    container_name: db-service
    ports:
      - "8300:8300"
    depends_on:
      - eureka-server
    links:
      - eureka-server
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka

  stock-service:
    image: stock-service
    container_name: stock-service
    ports:
      - "8305:8305"
    depends_on:
      - eureka-server
    links:
      - eureka-server
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka